"""GitHub adapter — emit governance config from a charter.

Unlike the humanlayer/langgraph stubs, this target is **real**: it turns a
charter's gates and accountability into a CODEOWNERS starting point and a
branch-protection checklist you apply in GitHub. AgenRACI still does not enforce
anything at runtime — this is static config a human reviews and commits. A
charter governs action *types*, not file paths, so the CODEOWNERS lines are a
scaffold you scope to your repo.
"""

from __future__ import annotations

import base64
import json
import re
import subprocess
from dataclasses import dataclass, field

from ..schema import Charter


def _humans_in_role(charter: Charter, role: str) -> list[str]:
    """Human members holding ``role`` (agents can't be GitHub code owners)."""
    return [m.name for m in charter.members if m.role == role and m.type == "human"]


def _handles(names: list[str]) -> str:
    return " ".join(f"@{n}" for n in names)


def compile(charter: Charter) -> str:  # noqa: A001 - mirror CLI "compile" verb
    """Emit CODEOWNERS + branch-protection guidance derived from the charter."""
    out: list[str] = []
    out.append(f"# GitHub governance for {charter.project}")
    out.append("# Generated by `agenraci compile --target github`.")
    out.append("# AgenRACI does not enforce anything at runtime — review this, map the")
    out.append("# member names to GitHub @handles, and apply it in GitHub yourself.")
    out.append("")

    gated = {name: a for name, a in charter.actions.items() if a.gate is not None}

    # --- CODEOWNERS scaffold --------------------------------------------------
    out.append("# ── CODEOWNERS (starting point) ─────────────────────────────────")
    out.append("# A charter governs action TYPES, not file paths, so scope the glob(s)")
    out.append("# below to the parts of your repo each owner is accountable for.")
    owners = sorted({
        h for a in gated.values() for r in a.accountable
        for h in _humans_in_role(charter, r)
    })
    if owners:
        out.append(f"*    {_handles(owners)}")
    else:
        out.append("# (no human is accountable for a gated action — set owners by hand)")
    out.append("")

    # --- Branch protection checklist -----------------------------------------
    out.append("# ── Branch protection (from gated actions) ──────────────────────")
    if not gated:
        out.append("# No action declares a `gate:`, so nothing here requires approval. Add a")
        out.append("# gate to the actions that must never happen unilaterally.")
        return "\n".join(out) + "\n"

    out.append("# In Settings → Branches → Add branch protection rule, for each action:")
    for name, action in gated.items():
        gate = action.gate
        approvers = _humans_in_role(charter, gate.approver)
        who = (
            _handles(approvers) if approvers
            else f"role '{gate.approver}' (no human members — assign one)"
        )
        out.append("")
        out.append(f"# {name}")
        out.append(f"#   • Require a pull request before merging, approved by {who}.")

        if gate.on_timeout == "block":
            out.append("#   • Do NOT enable auto-merge "
                       "(charter on_timeout=block — never proceeds unreviewed).")
        elif gate.on_timeout == "proceed_if_low_risk":
            out.append("#   • Auto-merge tolerable for this action only "
                       "(charter on_timeout=proceed_if_low_risk; it is marked low-risk).")
        elif gate.on_timeout.startswith("escalate_to:"):
            esc = gate.on_timeout.split(":", 1)[1].strip()
            out.append(f"#   • On approver timeout, route the decision to role '{esc}' "
                       f"(charter {gate.on_timeout}).")

        if gate.break_glass is not None:
            bg = gate.break_glass
            after = "after-the-fact review required" if bg.requires_after_review \
                else "no after-review required"
            out.append(f"#   • Break-glass: '{bg.who}' may override when {bg.condition} "
                       f"({after}).")

    # --- Applyable branch-protection JSON ------------------------------------
    # The checklist above is for a human reading; this block is for a human to
    # apply verbatim. It is GitHub's classic branch-protection PUT body, with the
    # exact fields `agenraci verify` reads back (see verify_github /
    # _classic_facts), so the compile→apply→verify loop closes: apply this, then
    # `agenraci verify CHARTER.yaml --repo OWNER/REPO` reports CLEAN against this charter.
    #
    # Derived strictly from the charter (the charter is a FLOOR, never inflated):
    #   • required_approving_review_count = 1 (the charter's minimum).
    #   • require_code_owner_reviews = true iff a HUMAN is accountable for some
    #     gated action; with no human accountable, code owners can't be enforced
    #     (owners must be human) so we don't pretend they are.
    require_code_owner_reviews = bool(owners)
    protection_body = {
        "required_status_checks": None,
        "enforce_admins": True,
        "required_pull_request_reviews": {
            "required_approving_review_count": 1,
            "require_code_owner_reviews": require_code_owner_reviews,
        },
        "restrictions": None,
    }

    has_block_gate = any(a.gate.on_timeout == "block" for a in gated.values())

    out.append("")
    out.append("# ── Applyable branch protection (classic) ───────────────────────")
    out.append("# This is GitHub's branch-protection PUT body. AgenRACI does NOT apply")
    out.append("# it — you run the command below yourself. Save the JSON to a file (it")
    out.append("# is everything between the BEGIN/END markers), set OWNER/REPO/BRANCH,")
    out.append("# then apply and verify:")
    out.append("#")
    out.append("#   gh api repos/OWNER/REPO/branches/BRANCH/protection \\")
    out.append("#     --method PUT --input protection.json")
    out.append("#   agenraci verify CHARTER.yaml --repo OWNER/REPO   # should report CLEAN")
    if not require_code_owner_reviews:
        out.append("#")
        out.append("# Note: no human is accountable for a gated action, so code-owner")
        out.append("# review is left OFF (GitHub code owners must be human — requiring it")
        out.append("# would enforce nothing). Reviews are still required.")
    if has_block_gate:
        out.append("#")
        out.append("# A gated action declares on_timeout=block, so it must never proceed")
        out.append("# unreviewed. Auto-merge is a REPO setting (not in this PUT body) —")
        out.append("# turn it off at the repo level:")
        out.append("#")
        out.append("#   gh api repos/OWNER/REPO --method PATCH -f allow_auto_merge=false")
    out.append("# --- BEGIN protection.json ---")
    out.extend(json.dumps(protection_body, indent=2).splitlines())
    out.append("# --- END protection.json ---")

    return "\n".join(out) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# verify: does a live repo actually enforce what the charter declares?
#
# AgenRACI still does not intercept anything. `verify` is read-only: it compares
# the charter against a repo's protection settings and reports drift. The live
# (`gh api`) and offline (committed export) paths both normalise GitHub's two
# protection models — classic branch protection and rulesets — into one
# ``GitHubProtection`` before comparison, so the comparison core never sees the
# raw API shapes.
#
#   charter ─┐
#            ├─▶ verify_github() ─▶ VerifyReport ─▶ json / human
#   GitHubProtection ─┘             (drift? + unenforceable + note)
#       ▲
#       └── parse_protection(export dict)  |  fetch_live_protection (gh api → same shape)
#
# Comparison model (deliberately NOT path globs — the human owns scoping):
#   • owner-set: accountable HUMANS across gated actions ⊆ live CODEOWNERS owners
#   • branch-protection facts: ≥1 required review, code-owner review required
#   • strictest-wins: any gated on_timeout=block ⇒ auto-merge must be off
#   • directionality: the charter is a FLOOR — a stricter repo PASSES (subset/≥)
#   • agent-only-accountable actions are UNENFORCEABLE (code owners must be human),
#     reported explicitly so a green result never means "nothing was verified".
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class GitHubProtection:
    """Normalised protection settings for one branch.

    Both GitHub protection models (classic branch protection and rulesets) and
    an offline export collapse to this shape before comparison.
    """

    branch: str
    required_reviews: int = 0
    require_code_owner_review: bool = False
    code_owners: list[str] = field(default_factory=list)  # @-stripped handles
    allow_auto_merge: bool = False


@dataclass
class VerifyFinding:
    target: str  # an action name, or the branch
    kind: str  # "drift" | "unenforceable"
    message: str


@dataclass
class VerifyReport:
    project: str
    branch: str
    ok: bool
    findings: list[VerifyFinding]  # drift only — these flip ok to False
    unenforceable: list[VerifyFinding]
    note: str | None = None


def parse_protection(data: dict, *, branch: str = "main") -> GitHubProtection:
    """Build a ``GitHubProtection`` from a normalised export dict.

    The offline (`--settings`) input uses this documented shape::

        {"branch": "main", "required_reviews": 1,
         "require_code_owner_review": true,
         "code_owners": ["alice", "bob"], "allow_auto_merge": false}

    Parsing GitHub's raw classic-protection and ruleset API shapes into this
    normalised form (for live mode and real exports) lands in the next increment.
    """
    owners = [str(o).lstrip("@") for o in data.get("code_owners", [])]
    return GitHubProtection(
        branch=str(data.get("branch", branch)),
        required_reviews=int(data.get("required_reviews", 0)),
        require_code_owner_review=bool(data.get("require_code_owner_review", False)),
        code_owners=owners,
        allow_auto_merge=bool(data.get("allow_auto_merge", False)),
    )


def verify_github(
    charter: Charter, protection: GitHubProtection, *, branch: str = "main"
) -> VerifyReport:
    """Compare a charter against a branch's live protection. Read-only."""
    gated = {n: a for n, a in charter.actions.items() if a.gate is not None}
    if not gated:
        return VerifyReport(
            project=charter.project, branch=branch, ok=True, findings=[],
            unenforceable=[],
            note="No action declares a gate, so nothing requires enforcement.",
        )

    drift: list[VerifyFinding] = []
    unenforceable: list[VerifyFinding] = []

    # Expected owners = accountable humans across gated actions. A gated action
    # whose accountable role(s) have no human member is unenforceable (code
    # owners must be human), surfaced explicitly — never silently skipped.
    expected: set[str] = set()
    for name, action in gated.items():
        humans = {h for r in action.accountable for h in _humans_in_role(charter, r)}
        if humans:
            expected.update(humans)
        else:
            unenforceable.append(VerifyFinding(
                name, "unenforceable",
                f"accountable role(s) {', '.join(action.accountable)} have no human "
                "members; GitHub code owners must be human, so this action can't be "
                "enforced via CODEOWNERS.",
            ))

    actual = set(protection.code_owners)
    missing = sorted(expected - actual)  # subset check: a repo may have MORE owners
    if missing:
        drift.append(VerifyFinding(
            branch, "drift",
            "CODEOWNERS is missing accountable owner(s): "
            + ", ".join(f"@{m}" for m in missing) + ".",
        ))

    if protection.required_reviews < 1:
        drift.append(VerifyFinding(
            branch, "drift",
            "branch protection requires no approving review; the charter's gated "
            "actions need at least one.",
        ))

    if expected and not protection.require_code_owner_review:
        drift.append(VerifyFinding(
            branch, "drift",
            "branch protection does not require review from code owners, so the "
            "accountable owners are not actually enforced.",
        ))

    if protection.allow_auto_merge and any(
        a.gate.on_timeout == "block" for a in gated.values()
    ):
        drift.append(VerifyFinding(
            branch, "drift",
            "auto-merge is enabled but a gated action declares on_timeout=block "
            "(it must never proceed unreviewed).",
        ))

    return VerifyReport(
        project=charter.project, branch=branch, ok=not drift,
        findings=drift, unenforceable=unenforceable, note=None,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Live mode: read a repo's real protection via `gh api`, normalise into a
# GitHubProtection, and hand it to verify_github. GitHub exposes protection two
# ways — classic branch protection and rulesets (which can also come from the
# org) — so we read BOTH and take the union (max reviews, OR code-owner-review).
# A 404 on the classic-protection endpoint means "no classic protection", not an
# error; a repo-level 404/401/403 or a missing `gh` means we COULD NOT CHECK
# (distinct from drift — never a pass, never a fail).
#
#   gh api  ─▶ _classic_facts ┐
#           ─▶ _ruleset_facts ┼─▶ protection_from_github ─▶ GitHubProtection
#           ─▶ repo.allow_auto_merge ┘        ▲
#           ─▶ CODEOWNERS file ──▶ parse_codeowners ┘
# ─────────────────────────────────────────────────────────────────────────────


class CouldNotCheck(Exception):
    """verify could not read the live settings (no gh, auth, network, bad repo).

    Distinct from drift: the CLI maps this to exit code 2, never to a pass or a
    fail. A missing protection rule is *drift*; an inability to look is *this*.
    """


_OWNER_RE = re.compile(r"@([A-Za-z0-9][A-Za-z0-9/_.-]*)")
_CODEOWNERS_PATHS = (".github/CODEOWNERS", "CODEOWNERS", "docs/CODEOWNERS")


def parse_codeowners(text: str) -> list[str]:
    """Owners mentioned anywhere in a CODEOWNERS file, ``@`` stripped.

    We deliberately do NOT model path globs (the human owns scoping), so this
    returns the union of every owner across all rules. ``@org/team`` entries come
    back as ``org/team`` and email owners (``user@example.com``) as the domain —
    neither matches an individual human name, a known limitation when a repo
    scopes ownership to teams or emails (harmless to the subset check: a spurious
    extra owner never causes drift).
    """
    owners: set[str] = set()
    for raw in text.splitlines():
        line = raw.split("#", 1)[0]
        for m in _OWNER_RE.finditer(line):
            owners.add(m.group(1))
    return sorted(owners)


def _classic_facts(protection: dict | None) -> tuple[int, bool]:
    if not protection:
        return (0, False)
    rpr = protection.get("required_pull_request_reviews") or {}
    return (
        int(rpr.get("required_approving_review_count", 0) or 0),
        bool(rpr.get("require_code_owner_reviews", False)),
    )


def _ruleset_facts(rules: list | None) -> tuple[int, bool]:
    count, code_owner = 0, False
    for rule in rules or []:
        if rule.get("type") == "pull_request":
            params = rule.get("parameters") or {}
            count = max(count, int(params.get("required_approving_review_count", 0) or 0))
            code_owner = code_owner or bool(params.get("require_code_owner_review", False))
    return (count, code_owner)


def protection_from_github(
    *,
    branch: str,
    protection: dict | None = None,
    rules: list | None = None,
    repo: dict | None = None,
    codeowners: str | None = None,
) -> GitHubProtection:
    """Normalise GitHub's raw API shapes into one GitHubProtection.

    classic + rulesets are unioned: required reviews = max, code-owner review =
    either. ``allow_auto_merge`` is a repo setting; ``code_owners`` come from the
    CODEOWNERS file. Any source may be ``None`` (contributes its default).
    """
    c_count, c_co = _classic_facts(protection)
    r_count, r_co = _ruleset_facts(rules)
    return GitHubProtection(
        branch=branch,
        required_reviews=max(c_count, r_count),
        require_code_owner_review=(c_co or r_co),
        code_owners=parse_codeowners(codeowners) if codeowners else [],
        allow_auto_merge=bool((repo or {}).get("allow_auto_merge", False)),
    )


def _default_runner(argv: list[str]) -> tuple[int, str, str]:
    """Run a command, return (returncode, stdout, stderr). Injectable for tests."""
    try:
        p = subprocess.run(argv, capture_output=True, text=True, timeout=30)
    except FileNotFoundError as exc:
        raise CouldNotCheck("the `gh` CLI is not installed or not on PATH.") from exc
    except subprocess.TimeoutExpired as exc:
        raise CouldNotCheck("`gh api` timed out.") from exc
    return (p.returncode, p.stdout, p.stderr)


def _gh_api(runner, path: str, *, allow_404: bool = False):
    """Call ``gh api <path>``; parse JSON. ``allow_404`` returns None on 404."""
    rc, out, err = runner(["gh", "api", path])
    if rc == 0:
        try:
            return json.loads(out) if out.strip() else None
        except json.JSONDecodeError as exc:
            raise CouldNotCheck(f"gh api {path}: unparseable response") from exc
    low = (err or "").lower()
    if allow_404 and ("404" in low or "not found" in low):
        return None
    if any(k in low for k in ("auth", "login", "401", "403", "forbidden")):
        raise CouldNotCheck(f"gh api {path}: not authenticated/authorised "
                            f"({err.strip().splitlines()[0] if err.strip() else 'auth error'})")
    raise CouldNotCheck(f"gh api {path}: {err.strip().splitlines()[0] if err.strip() else 'failed'}")


def _fetch_codeowners(runner, repo: str, branch: str) -> str | None:
    """Return the first CODEOWNERS file found among the standard locations."""
    for path in _CODEOWNERS_PATHS:
        obj = _gh_api(runner, f"repos/{repo}/contents/{path}?ref={branch}", allow_404=True)
        if obj and obj.get("encoding") == "base64" and obj.get("content"):
            return base64.b64decode(obj["content"]).decode("utf-8", "replace")
    return None


def fetch_live_protection(repo: str, branch: str, *, runner=None) -> GitHubProtection:
    """Read a repo's live protection via ``gh api`` and normalise it.

    Raises CouldNotCheck on any inability to read (no gh, auth, bad repo). A
    missing classic-protection rule or missing CODEOWNERS is NOT an error — it
    just contributes nothing (and likely shows up as drift, which is correct).
    """
    runner = runner or _default_runner
    # repos/{repo} first: a 404/403 here is a real "couldn't check" (bad repo or
    # no access), not the benign "no protection configured" 404 below.
    repo_obj = _gh_api(runner, f"repos/{repo}")
    protection = _gh_api(
        runner, f"repos/{repo}/branches/{branch}/protection", allow_404=True)
    rules = _gh_api(
        runner, f"repos/{repo}/rules/branches/{branch}", allow_404=True) or []
    codeowners = _fetch_codeowners(runner, repo, branch)
    return protection_from_github(
        branch=branch, protection=protection, rules=rules,
        repo=repo_obj, codeowners=codeowners,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Org sweep: run verify across every repo in an org against one charter, and
# aggregate. The killer governance-audit scenario — "does every repo in our org
# enforce our accountability rules?". One repo that can't be read is isolated
# (reported could-not-check) so it never crashes the sweep; the overall result
# fails only on actual drift.
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class RepoResult:
    repo: str
    status: str  # "clean" | "drift" | "could-not-check"
    report: VerifyReport | None = None
    error: str | None = None


@dataclass
class OrgSweepReport:
    org: str
    branch: str
    results: list[RepoResult]
    ok: bool  # True if no repo drifted (could-not-check does not flip ok)
    truncated: bool = False  # the org has MORE repos than the listing limit


def _list_org_repos(org: str, *, runner, limit: int = 1000) -> list[str]:
    """Every repo's ``owner/name`` in an org (via ``gh repo list``)."""
    rc, out, err = runner(
        ["gh", "repo", "list", org, "--limit", str(limit), "--json", "nameWithOwner"])
    if rc != 0:
        first = err.strip().splitlines()[0] if err.strip() else "failed"
        raise CouldNotCheck(f"gh repo list {org}: {first}")
    try:
        data = json.loads(out) if out.strip() else []
    except json.JSONDecodeError as exc:
        raise CouldNotCheck(f"gh repo list {org}: unparseable response") from exc
    return [r["nameWithOwner"] for r in data]


def sweep_org(
    charter: Charter, org: str, *, branch: str = "main", runner=None, limit: int = 1000
) -> OrgSweepReport:
    """Verify every repo in ``org`` against one charter, aggregating the result.

    Listing the org is itself a could-not-check failure (raises CouldNotCheck);
    a single repo that can't be read is isolated into a per-repo
    ``could-not-check`` result so the rest of the sweep still runs. If the org has
    more repos than ``limit``, ``truncated`` is set so a clean verdict is never
    mistaken for a complete audit.
    """
    runner = runner or _default_runner
    repos = _list_org_repos(org, runner=runner, limit=limit)
    truncated = len(repos) >= limit
    results: list[RepoResult] = []
    any_drift = False
    for repo in repos:
        try:
            protection = fetch_live_protection(repo, branch, runner=runner)
        except CouldNotCheck as exc:
            results.append(RepoResult(repo, "could-not-check", error=str(exc)))
            continue
        report = verify_github(charter, protection, branch=branch)
        if report.ok:
            results.append(RepoResult(repo, "clean", report=report))
        else:
            any_drift = True
            results.append(RepoResult(repo, "drift", report=report))
    return OrgSweepReport(org=org, branch=branch, results=results,
                          ok=not any_drift, truncated=truncated)
