"""GitHub adapter — emit governance config from a charter.

Unlike the humanlayer/langgraph stubs, this target is **real**: it turns a
charter's gates and accountability into a CODEOWNERS starting point and a
branch-protection checklist you apply in GitHub. AgenRACI still does not enforce
anything at runtime — this is static config a human reviews and commits. A
charter governs action *types*, not file paths, so the CODEOWNERS lines are a
scaffold you scope to your repo.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ..schema import Charter


def _humans_in_role(charter: Charter, role: str) -> list[str]:
    """Human members holding ``role`` (agents can't be GitHub code owners)."""
    return [m.name for m in charter.members if m.role == role and m.type == "human"]


def _handles(names: list[str]) -> str:
    return " ".join(f"@{n}" for n in names)


def compile(charter: Charter) -> str:  # noqa: A001 - mirror CLI "compile" verb
    """Emit CODEOWNERS + branch-protection guidance derived from the charter."""
    out: list[str] = []
    out.append(f"# GitHub governance for {charter.project}")
    out.append("# Generated by `agenraci compile --target github`.")
    out.append("# AgenRACI does not enforce anything at runtime — review this, map the")
    out.append("# member names to GitHub @handles, and apply it in GitHub yourself.")
    out.append("")

    gated = {name: a for name, a in charter.actions.items() if a.gate is not None}

    # --- CODEOWNERS scaffold --------------------------------------------------
    out.append("# ── CODEOWNERS (starting point) ─────────────────────────────────")
    out.append("# A charter governs action TYPES, not file paths, so scope the glob(s)")
    out.append("# below to the parts of your repo each owner is accountable for.")
    owners = sorted({
        h for a in gated.values() for r in a.accountable
        for h in _humans_in_role(charter, r)
    })
    if owners:
        out.append(f"*    {_handles(owners)}")
    else:
        out.append("# (no human is accountable for a gated action — set owners by hand)")
    out.append("")

    # --- Branch protection checklist -----------------------------------------
    out.append("# ── Branch protection (from gated actions) ──────────────────────")
    if not gated:
        out.append("# No action declares a `gate:`, so nothing here requires approval. Add a")
        out.append("# gate to the actions that must never happen unilaterally.")
        return "\n".join(out) + "\n"

    out.append("# In Settings → Branches → Add branch protection rule, for each action:")
    for name, action in gated.items():
        gate = action.gate
        approvers = _humans_in_role(charter, gate.approver)
        who = (
            _handles(approvers) if approvers
            else f"role '{gate.approver}' (no human members — assign one)"
        )
        out.append("")
        out.append(f"# {name}")
        out.append(f"#   • Require a pull request before merging, approved by {who}.")

        if gate.on_timeout == "block":
            out.append("#   • Do NOT enable auto-merge "
                       "(charter on_timeout=block — never proceeds unreviewed).")
        elif gate.on_timeout == "proceed_if_low_risk":
            out.append("#   • Auto-merge tolerable for this action only "
                       "(charter on_timeout=proceed_if_low_risk; it is marked low-risk).")
        elif gate.on_timeout.startswith("escalate_to:"):
            esc = gate.on_timeout.split(":", 1)[1].strip()
            out.append(f"#   • On approver timeout, route the decision to role '{esc}' "
                       f"(charter {gate.on_timeout}).")

        if gate.break_glass is not None:
            bg = gate.break_glass
            after = "after-the-fact review required" if bg.requires_after_review \
                else "no after-review required"
            out.append(f"#   • Break-glass: '{bg.who}' may override when {bg.condition} "
                       f"({after}).")

    return "\n".join(out) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# verify: does a live repo actually enforce what the charter declares?
#
# AgenRACI still does not intercept anything. `verify` is read-only: it compares
# the charter against a repo's protection settings and reports drift. The live
# (`gh api`) and offline (committed export) paths both normalise GitHub's two
# protection models — classic branch protection and rulesets — into one
# ``GitHubProtection`` before comparison, so the comparison core never sees the
# raw API shapes.
#
#   charter ─┐
#            ├─▶ verify_github() ─▶ VerifyReport ─▶ json / human
#   GitHubProtection ─┘             (drift? + unenforceable + note)
#       ▲
#       └── parse_protection(export dict)  |  (live: gh api → same shape, later)
#
# Comparison model (deliberately NOT path globs — the human owns scoping):
#   • owner-set: accountable HUMANS across gated actions ⊆ live CODEOWNERS owners
#   • branch-protection facts: ≥1 required review, code-owner review required
#   • strictest-wins: any gated on_timeout=block ⇒ auto-merge must be off
#   • directionality: the charter is a FLOOR — a stricter repo PASSES (subset/≥)
#   • agent-only-accountable actions are UNENFORCEABLE (code owners must be human),
#     reported explicitly so a green result never means "nothing was verified".
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class GitHubProtection:
    """Normalised protection settings for one branch.

    Both GitHub protection models (classic branch protection and rulesets) and
    an offline export collapse to this shape before comparison.
    """

    branch: str
    required_reviews: int = 0
    require_code_owner_review: bool = False
    code_owners: list[str] = field(default_factory=list)  # @-stripped handles
    allow_auto_merge: bool = False


@dataclass
class VerifyFinding:
    target: str  # an action name, or the branch
    kind: str  # "drift" | "unenforceable"
    message: str


@dataclass
class VerifyReport:
    project: str
    branch: str
    ok: bool
    findings: list[VerifyFinding]  # drift only — these flip ok to False
    unenforceable: list[VerifyFinding]
    note: str | None = None


def parse_protection(data: dict, *, branch: str = "main") -> GitHubProtection:
    """Build a ``GitHubProtection`` from a normalised export dict.

    The offline (`--settings`) input uses this documented shape::

        {"branch": "main", "required_reviews": 1,
         "require_code_owner_review": true,
         "code_owners": ["alice", "bob"], "allow_auto_merge": false}

    Parsing GitHub's raw classic-protection and ruleset API shapes into this
    normalised form (for live mode and real exports) lands in the next increment.
    """
    owners = [str(o).lstrip("@") for o in data.get("code_owners", [])]
    return GitHubProtection(
        branch=str(data.get("branch", branch)),
        required_reviews=int(data.get("required_reviews", 0)),
        require_code_owner_review=bool(data.get("require_code_owner_review", False)),
        code_owners=owners,
        allow_auto_merge=bool(data.get("allow_auto_merge", False)),
    )


def verify_github(
    charter: Charter, protection: GitHubProtection, *, branch: str = "main"
) -> VerifyReport:
    """Compare a charter against a branch's live protection. Read-only."""
    gated = {n: a for n, a in charter.actions.items() if a.gate is not None}
    if not gated:
        return VerifyReport(
            project=charter.project, branch=branch, ok=True, findings=[],
            unenforceable=[],
            note="No action declares a gate, so nothing requires enforcement.",
        )

    drift: list[VerifyFinding] = []
    unenforceable: list[VerifyFinding] = []

    # Expected owners = accountable humans across gated actions. A gated action
    # whose accountable role(s) have no human member is unenforceable (code
    # owners must be human), surfaced explicitly — never silently skipped.
    expected: set[str] = set()
    for name, action in gated.items():
        humans = {h for r in action.accountable for h in _humans_in_role(charter, r)}
        if humans:
            expected.update(humans)
        else:
            unenforceable.append(VerifyFinding(
                name, "unenforceable",
                f"accountable role(s) {', '.join(action.accountable)} have no human "
                "members; GitHub code owners must be human, so this action can't be "
                "enforced via CODEOWNERS.",
            ))

    actual = set(protection.code_owners)
    missing = sorted(expected - actual)  # subset check: a repo may have MORE owners
    if missing:
        drift.append(VerifyFinding(
            branch, "drift",
            "CODEOWNERS is missing accountable owner(s): "
            + ", ".join(f"@{m}" for m in missing) + ".",
        ))

    if protection.required_reviews < 1:
        drift.append(VerifyFinding(
            branch, "drift",
            "branch protection requires no approving review; the charter's gated "
            "actions need at least one.",
        ))

    if expected and not protection.require_code_owner_review:
        drift.append(VerifyFinding(
            branch, "drift",
            "branch protection does not require review from code owners, so the "
            "accountable owners are not actually enforced.",
        ))

    if protection.allow_auto_merge and any(
        a.gate.on_timeout == "block" for a in gated.values()
    ):
        drift.append(VerifyFinding(
            branch, "drift",
            "auto-merge is enabled but a gated action declares on_timeout=block "
            "(it must never proceed unreviewed).",
        ))

    return VerifyReport(
        project=charter.project, branch=branch, ok=not drift,
        findings=drift, unenforceable=unenforceable, note=None,
    )
